version: "3.9"
services:
  bank-api:
    build:
      context: .
      dockerfile: src/Checkout.TakeHomeChallenge.BankSimulator/Dockerfile
  
  payment-gateway:
    build:
      context: .
      dockerfile: src/Checkout.TakeHomeChallenge.PaymentGateway/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Test
    volumes:
      - ./appsettings.docker-compose.payment-gateway.json:/app/appsettings.Test.json
  
  k6:
    image: grafana/k6:0.38.3
    profiles:
      - test
    depends_on: 
      - bank-api
      - payment-gateway
      - postgres
    volumes:
      - ./tests/Checkout.TakeHomeChallenge.PaymentGateway.LoadTest/script.js:/script.js
    entrypoint: k6 run /script.js

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=123